#!/usr/bin/env python3
"""verilog_a_validate.py — Pillar IV.1 ngspice/pyport validation harness.

Compares Id(Vd, VG1, VG2) between:
    (a) The pyport at nsram/nsram/bsim4_port/nsram_cell_2T.py
    (b) The exported Verilog-A model at nsram/verilog_a/nsram_cell_2T.va,
        either via OpenVAF→ngspice OSDI, or via an ngspice subcircuit
        surrogate (`nsram_cell_2T_subckt.sp`) using built-in M/Q/D
        primitives.

Today's scope (Pillar IV.1):
    * verify the .va file PARSES (we drive an OpenVAF build attempt if
      openvaf is available)
    * generate the subcircuit surrogate
    * run one bias point (VG1=0.6, VG2=0.0, Vd=0.5) through both engines
    * print max-RMSE (full 33-bias sweep gate is for tomorrow IV.2)
"""
from __future__ import annotations
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
VA_FILE   = REPO / "nsram" / "verilog_a" / "nsram_cell_2T.va"
SUBCKT_SP = REPO / "nsram" / "verilog_a" / "nsram_cell_2T_subckt.sp"
RESULTS   = REPO / "results" / "Pillar_IV_1_va_export"
RESULTS.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# 1.  Verilog-A parse check (best-effort)
# ---------------------------------------------------------------------------

def try_openvaf_compile() -> tuple[bool, str]:
    """Attempt to compile the .va with openvaf if available."""
    openvaf = shutil.which("openvaf")
    if not openvaf:
        return False, "openvaf not found in PATH (skipping VA compile)"
    out = REPO / "results" / "Pillar_IV_1_va_export" / "nsram_cell_2T.osdi"
    proc = subprocess.run(
        [openvaf, str(VA_FILE), "-o", str(out)],
        capture_output=True, text=True, cwd=REPO,
    )
    msg = proc.stdout + proc.stderr
    return proc.returncode == 0, msg


# ---------------------------------------------------------------------------
# 2.  Subcircuit surrogate (primitive-level ngspice equivalent)
# ---------------------------------------------------------------------------

SUBCKT_TEMPLATE = """\
* nsram_cell_2T_subckt.sp -- primitive-level ngspice surrogate of nsram_cell_2T.va
* Auto-generated by scripts/verilog_a_validate.py
*
* Pins:   D  G1  G2  S  B
* Internal: Sint (M1.S = M2.D = Q1.E)
*
* Uses NMOS primitive + NPN BJT + body diodes.
* NOT a 1:1 surrogate of the pyport — see results/Pillar_IV_1_va_export/build_report.md

.subckt nsram_cell_2t  D G1 G2 S B
* M1: D=D, G=G1, S=Sint, B=B   (body floating)
M1 D G1 Sint B  nch  L=180n  W=360n
* M2: D=Sint, G=G2, S=S, B=S  (m2_body_gnd=1 default)
M2 Sint G2 S S  nch  L=1.8u  W=360n
* Parasitic NPN Q1: C=D, B=B, E=Sint
Q1 D B Sint  npnq
* Body diodes (M1 only -- M2 body tied to gnd already)
D1 B Sint  dbody
D2 B D     dbody
* Body cap
Cbody B 0 1f
.model nch    nmos  level=1  vto=0.45 kp=80u
+      gamma=0.30 phi=0.7 lambda=0.05
.model npnq   npn   is=6.0256e-9 bf=417 vaf=0.90 nf=1 br=1 nr=1
.model dbody  d     is=6.5e-18 n=1.0
.ends nsram_cell_2t
"""


def emit_subckt() -> None:
    SUBCKT_SP.write_text(SUBCKT_TEMPLATE)


# ---------------------------------------------------------------------------
# 3.  ngspice one-bias-point run
# ---------------------------------------------------------------------------

NGSPICE_DECK = """\
* nsram_cell_2T one-bias-point test
.include {subckt}

X1  d  g1 g2 0 b  nsram_cell_2t

Vd   d   0  DC {Vd}
Vg1  g1  0  DC {Vg1}
Vg2  g2  0  DC {Vg2}
* Body left floating except for internal Cbody to gnd; add 1G to anchor DC
Rb   b   0  1e9

.options gmin=1e-15 reltol=1e-6 abstol=1e-14
.op
.control
op
print v(d) v(g1) v(g2) v(b) i(Vd)
quit
.endc
.end
"""


def run_ngspice(Vd=0.5, Vg1=0.6, Vg2=0.0) -> tuple[float | None, str]:
    deck = NGSPICE_DECK.format(subckt=str(SUBCKT_SP), Vd=Vd, Vg1=Vg1, Vg2=Vg2)
    with tempfile.NamedTemporaryFile("w", suffix=".sp", delete=False) as f:
        f.write(deck)
        deck_path = f.name
    proc = subprocess.run(
        ["ngspice", "-b", deck_path],
        capture_output=True, text=True,
    )
    out = proc.stdout + proc.stderr
    # Parse "i(Vd) = <value>" line
    Id = None
    for line in out.splitlines():
        s = line.strip().lower()
        if s.startswith("i(vd)") and "=" in s:
            try:
                Id = float(s.split("=")[1].strip().split()[0])
            except Exception:
                pass
        # 'i(vd) = -1.234e-05' alt format
        if "i(vd)" in s and "=" not in s:
            parts = s.split()
            # ['i(vd)', 'value'] — common print format
            for tok in parts:
                try:
                    Id = float(tok)
                    break
                except Exception:
                    continue
    return Id, out


# ---------------------------------------------------------------------------
# 4.  Pyport one-bias-point (stub — full call wires up tomorrow)
# ---------------------------------------------------------------------------

def run_pyport(Vd=0.5, Vg1=0.6, Vg2=0.0) -> float | None:
    """Best-effort pyport call. Full canonical config wiring is IV.2."""
    try:
        sys.path.insert(0, str(REPO / "nsram"))
        from nsram.bsim4_port.nsram_cell_2T import (  # type: ignore
            NSRAMCell2TConfig, solve_2t_steady_state,
        )
        from nsram.bsim4_port.model_card import BSIM4Model  # type: ignore
        from nsram.bsim4_port.bjt import GummelPoonNPN  # type: ignore
        import torch
        cfg = NSRAMCell2TConfig()
        # Default model card: load PTM130bulkNSRAM SPICE card
        ptm_card = (REPO / "nsram" / "data" / "sebas_2026_04_22"
                    / "PTM130bulkNSRAM.txt").read_text()
        model = BSIM4Model.from_spice(ptm_card, model_type="nmos")
        bjt = GummelPoonNPN()
        Vd_t  = torch.tensor([Vd],  dtype=torch.float64)
        Vg1_t = torch.tensor([Vg1], dtype=torch.float64)
        Vg2_t = torch.tensor([Vg2], dtype=torch.float64)
        sol = solve_2t_steady_state(cfg, model, bjt, Vd_t, Vg1_t, Vg2_t)
        return float(sol["Id"].detach().cpu().item())
    except Exception as e:
        print(f"  [pyport] skipped: {e}", file=sys.stderr)
        return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    print("=" * 72)
    print("Pillar IV.1 — Verilog-A export validation harness")
    print("=" * 72)

    # 1. Parse / compile attempt
    print("\n[1/3]  Verilog-A parse check")
    ok, msg = try_openvaf_compile()
    print(f"       OpenVAF compile : {'OK' if ok else 'SKIPPED'}")
    if msg:
        print("       " + msg.strip().replace("\n", "\n       "))

    # 2. Emit + simulate the subcircuit surrogate
    print("\n[2/3]  ngspice subcircuit surrogate")
    emit_subckt()
    print(f"       Wrote {SUBCKT_SP}")
    Id_spice, log = run_ngspice()
    print(f"       Id_spice(VG1=0.6,VG2=0.0,Vd=0.5) = {Id_spice}")
    (RESULTS / "ngspice_log.txt").write_text(log)

    # 3. Pyport reference
    print("\n[3/3]  pyport reference")
    Id_py = run_pyport()
    print(f"       Id_pyport = {Id_py}")

    if Id_spice is not None and Id_py is not None:
        rmse = abs(Id_spice - Id_py)
        print(f"\n       |Id_spice - Id_pyport| = {rmse:.3e}  A")
        gate = rmse <= 1e-6
        print(f"       Gate (≤ 1e-6 A)         : {'PASS' if gate else 'FAIL (expected — IV.1 not at full BSIM4 fidelity)'}")
    else:
        print("\n       Comparison skipped (one side missing); see logs.")

    print("\nDone.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
