#!/usr/bin/env python3
"""
z1903: Hypernetwork Embodiment

RADICAL APPROACH: Telemetry GENERATES model weights.
Computation literally cannot happen without telemetry because weights don't exist!

Previous approaches (FiLM, gating, routing) all failed because the model could
learn to work around them. The task (LM) doesn't require hardware info.

HyperNetwork solution:
1. Telemetry -> Weight Generator -> Layer Weights
2. The computation CANNOT proceed without telemetry generating weights
3. Different telemetry = Different weights = Different computation

This is TRUE causal dependence - not conditioning, but generation.

Author: Claude
Date: 2026-02-05
"""

import os
import sys
import json
import time
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Tuple, Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.z1900_tri_hardware_consciousness import TriHardwareTelemetry


class HyperLinear(nn.Module):
    """Linear layer where weights are GENERATED by telemetry."""

    def __init__(self, in_features: int, out_features: int, telemetry_dim: int, rank: int = 32):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.rank = rank

        # Base weights (learned but modulated)
        self.weight_base = nn.Parameter(torch.randn(out_features, in_features) * 0.02)
        self.bias = nn.Parameter(torch.zeros(out_features))

        # Hypernetwork: telemetry -> low-rank weight modulation
        # Weight = base + U @ telemetry_proj @ V^T
        self.U = nn.Parameter(torch.randn(out_features, rank) * 0.01)
        self.V = nn.Parameter(torch.randn(in_features, rank) * 0.01)
        self.telem_proj = nn.Linear(telemetry_dim, rank)

    def forward(self, x: torch.Tensor, telemetry: torch.Tensor) -> torch.Tensor:
        # Generate weight modulation from telemetry
        telem_factor = self.telem_proj(telemetry)  # [B, rank]

        # Outer product modulation: U @ diag(telem) @ V^T
        # For each batch element, different weights!
        B = x.shape[0]

        # Compute telemetry-dependent weights
        # W = base + sum_r(U[:, r] * telem[r] * V[:, r]^T)
        modulation = torch.einsum('or,br,ir->boi', self.U, telem_factor, self.V)  # [B, out, in]

        # Full weight per batch
        weight = self.weight_base.unsqueeze(0) + modulation  # [B, out, in]

        # Batched matmul: each sample uses its own generated weights!
        # x: [B, *, in] -> out: [B, *, out]
        orig_shape = x.shape[:-1]
        x_flat = x.reshape(B, -1, self.in_features)  # [B, S, in]
        out = torch.bmm(x_flat, weight.transpose(-2, -1))  # [B, S, out]
        out = out.reshape(*orig_shape, self.out_features) + self.bias

        return out


class HyperAttention(nn.Module):
    """Attention where Q, K projections are generated by telemetry."""

    def __init__(self, hidden_dim: int, num_heads: int, telemetry_dim: int):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = hidden_dim // num_heads

        # Q and K are hyper-generated (telemetry-dependent)
        self.q_hyper = HyperLinear(hidden_dim, hidden_dim, telemetry_dim)
        self.k_hyper = HyperLinear(hidden_dim, hidden_dim, telemetry_dim)

        # V and output are standard (not telemetry-dependent)
        self.v_proj = nn.Linear(hidden_dim, hidden_dim)
        self.out_proj = nn.Linear(hidden_dim, hidden_dim)

    def forward(self, x: torch.Tensor, telemetry: torch.Tensor) -> torch.Tensor:
        B, S, D = x.shape

        # Q and K are telemetry-generated!
        Q = self.q_hyper(x, telemetry)  # Uses telemetry-generated weights
        K = self.k_hyper(x, telemetry)  # Uses telemetry-generated weights
        V = self.v_proj(x)

        Q = Q.view(B, S, self.num_heads, self.head_dim).transpose(1, 2)
        K = K.view(B, S, self.num_heads, self.head_dim).transpose(1, 2)
        V = V.view(B, S, self.num_heads, self.head_dim).transpose(1, 2)

        attn = F.softmax(Q @ K.transpose(-2, -1) / (self.head_dim ** 0.5), dim=-1)
        out = attn @ V

        out = out.transpose(1, 2).contiguous().view(B, S, D)
        return self.out_proj(out)


class HyperMLP(nn.Module):
    """MLP where first projection is telemetry-generated."""

    def __init__(self, hidden_dim: int, ff_dim: int, telemetry_dim: int):
        super().__init__()

        # First layer is hyper-generated
        self.fc1_hyper = HyperLinear(hidden_dim, ff_dim, telemetry_dim)

        # Second layer is standard
        self.fc2 = nn.Linear(ff_dim, hidden_dim)
        self.act = nn.GELU()

    def forward(self, x: torch.Tensor, telemetry: torch.Tensor) -> torch.Tensor:
        x = self.fc1_hyper(x, telemetry)  # Telemetry generates these weights!
        x = self.act(x)
        x = self.fc2(x)
        return x


class HyperBlock(nn.Module):
    """Transformer block with hypernetwork-generated attention and MLP."""

    def __init__(self, hidden_dim: int, num_heads: int, ff_dim: int, telemetry_dim: int):
        super().__init__()
        self.attn = HyperAttention(hidden_dim, num_heads, telemetry_dim)
        self.mlp = HyperMLP(hidden_dim, ff_dim, telemetry_dim)
        self.norm1 = nn.LayerNorm(hidden_dim)
        self.norm2 = nn.LayerNorm(hidden_dim)

    def forward(self, x: torch.Tensor, telemetry: torch.Tensor) -> torch.Tensor:
        x = x + self.attn(self.norm1(x), telemetry)
        x = x + self.mlp(self.norm2(x), telemetry)
        return x


class HyperEmbodiedTransformer(nn.Module):
    """Transformer where core computations are generated by telemetry."""

    def __init__(
        self,
        vocab_size: int = 256,
        hidden_dim: int = 384,
        num_layers: int = 6,
        num_heads: int = 6,
        ff_dim: int = 1536,
        telemetry_dim: int = 20,
    ):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, hidden_dim)
        self.pos_embedding = nn.Parameter(torch.randn(1, 1024, hidden_dim) * 0.02)

        # Mix of hyper and standard blocks
        # First 2 blocks: hyper-generated (telemetry critical)
        # Remaining blocks: standard (task learning)
        self.hyper_blocks = nn.ModuleList([
            HyperBlock(hidden_dim, num_heads, ff_dim, telemetry_dim)
            for _ in range(2)
        ])

        self.standard_blocks = nn.ModuleList([
            nn.TransformerEncoderLayer(
                d_model=hidden_dim,
                nhead=num_heads,
                dim_feedforward=ff_dim,
                batch_first=True,
                norm_first=True,
            )
            for _ in range(num_layers - 2)
        ])

        self.norm = nn.LayerNorm(hidden_dim)
        self.head = nn.Linear(hidden_dim, vocab_size)

        # Telemetry reconstruction (must flow through)
        self.telem_reconstruct = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.GELU(),
            nn.Linear(hidden_dim // 2, telemetry_dim),
        )

        self.vocab_size = vocab_size

    def forward(self, input_ids: torch.Tensor, telemetry: torch.Tensor, return_all: bool = False):
        B, S = input_ids.shape

        x = self.embedding(input_ids) + self.pos_embedding[:, :S, :]

        if telemetry.dim() == 1:
            telemetry = telemetry.unsqueeze(0).expand(B, -1)

        # Hyper blocks (telemetry generates weights!)
        for block in self.hyper_blocks:
            x = block(x, telemetry)

        # Standard blocks (task learning)
        for block in self.standard_blocks:
            x = block(x)

        x = self.norm(x)
        logits = self.head(x)

        # Reconstruct telemetry
        hidden_mean = x.mean(dim=1)
        telem_recon = self.telem_reconstruct(hidden_mean)

        if return_all:
            return {
                'logits': logits,
                'telem_reconstructed': telem_recon,
                'hidden_mean': hidden_mean,
            }
        return logits

    def count_parameters(self) -> int:
        return sum(p.numel() for p in self.parameters() if p.requires_grad)


def compute_signature(model, x, telem, device):
    """Compute behavioral signature."""
    model.eval()
    with torch.no_grad():
        out = model(x, telem, return_all=True)
        logits = out['logits']
        hidden = out['hidden_mean']

        return {
            'logit_entropy': -(F.softmax(logits, -1) * F.log_softmax(logits, -1)).sum(-1).mean().item(),
            'hidden_norm': hidden.norm(dim=-1).mean().item(),
            'hidden_std': hidden.std().item(),
            'output_mean': logits.mean().item(),
            'output_std': logits.std().item(),
        }


def signature_distance(s1, s2):
    diffs = []
    for k in s1:
        if k in s2 and abs(s1[k]) > 1e-6:
            diffs.append(abs(s1[k] - s2[k]) / abs(s1[k]))
    return np.mean(diffs) if diffs else 0.0


def run_experiment():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"[z1903] Device: {device}")
    print("[z1903] HYPERNETWORK EMBODIMENT")
    print("[z1903] Telemetry GENERATES model weights - TRUE causal dependence")

    # Telemetry
    telemetry = TriHardwareTelemetry()
    telemetry.start()
    time.sleep(1)

    hw_status = telemetry.get_hardware_status()
    print(f"[z1903] Hardware: GPU={hw_status['gpu']}, FPGA={hw_status['fpga']}, RF={hw_status['rf']}")

    # Data
    data_path = Path(__file__).parent.parent / "data" / "tinyshakespeare.txt"
    if not data_path.exists():
        data_path = Path(__file__).parent.parent / "tinyshakespeare.txt"
    text_bytes = data_path.read_text().encode('utf-8')

    # Model
    model = HyperEmbodiedTransformer(
        vocab_size=256,
        hidden_dim=384,
        num_layers=6,
        num_heads=6,
        ff_dim=1536,
        telemetry_dim=20,
    ).to(device)

    print(f"[z1903] Model parameters: {model.count_parameters():,}")

    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)

    batch_size = 4
    seq_len = 256
    epochs = 10
    batches_per_epoch = 150

    def get_batch():
        ix = torch.randint(len(text_bytes) - seq_len - 1, (batch_size,))
        x = torch.stack([torch.tensor(list(text_bytes[i:i+seq_len]), dtype=torch.long) for i in ix])
        y = torch.stack([torch.tensor(list(text_bytes[i+1:i+seq_len+1]), dtype=torch.long) for i in ix])
        return x.to(device), y.to(device)

    results = {
        'experiment': 'z1903_hypernetwork_embodiment',
        'timestamp': datetime.now().isoformat(),
        'device': str(device),
        'hardware_status': hw_status,
        'architecture': 'HyperNetwork (telemetry generates Q,K,MLP weights)',
    }

    # Training
    print("\n[z1903] Training with REAL telemetry (weights generated by hardware state)...")
    telem_samples = []

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0
        for _ in range(batches_per_epoch):
            x, y = get_batch()
            telem = telemetry.get_tensor().to(device)
            telem_samples.append(telem.cpu().numpy())

            optimizer.zero_grad()
            out = model(x, telem, return_all=True)

            task_loss = F.cross_entropy(out['logits'].view(-1, 256), y.view(-1))
            recon_loss = F.mse_loss(out['telem_reconstructed'], telem.unsqueeze(0).expand(batch_size, -1))

            loss = task_loss + 0.5 * recon_loss
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            epoch_loss += task_loss.item()

        print(f"  Epoch {epoch+1}/{epochs}: loss={epoch_loss/batches_per_epoch:.4f}")

    telem_samples = np.array(telem_samples)

    # Reference signature
    print("\n[z1903] Computing reference signature...")
    x_test, _ = get_batch()
    real_telem = telemetry.get_tensor().to(device)
    real_sig = compute_signature(model, x_test, real_telem, device)
    print(f"  Real: {real_sig}")

    # Falsification tests
    print("\n" + "="*60)
    print("[z1903] FALSIFICATION BATTERY")
    print("="*60)

    tests = {}

    # T1: Zero telemetry
    print("\n[z1903] T1: Zero Telemetry")
    zero_sig = compute_signature(model, x_test, torch.zeros(20, device=device), device)
    d1 = signature_distance(real_sig, zero_sig)
    print(f"  Distance: {d1:.4f}")
    tests['T1_zero'] = {'distance': d1, 'falsified': d1 < 0.05}

    # T2: Random telemetry
    print("\n[z1903] T2: Random Telemetry")
    d2_list = [signature_distance(real_sig, compute_signature(model, x_test, torch.rand(20, device=device), device)) for _ in range(10)]
    d2 = np.mean(d2_list)
    print(f"  Avg distance: {d2:.4f}")
    tests['T2_random'] = {'distance': d2, 'falsified': d2 < 0.05}

    # T3: Historical
    print("\n[z1903] T3: Historical Telemetry")
    old_telem = torch.tensor(telem_samples[0], device=device)
    d3 = signature_distance(real_sig, compute_signature(model, x_test, old_telem, device))
    print(f"  Distance: {d3:.4f}")
    tests['T3_historical'] = {'distance': d3, 'falsified': d3 < 0.03}

    # T4: Constant
    print("\n[z1903] T4: Constant Telemetry")
    mean_telem = torch.tensor(telem_samples.mean(0), device=device)
    d4 = signature_distance(real_sig, compute_signature(model, x_test, mean_telem, device))
    print(f"  Distance: {d4:.4f}")
    tests['T4_constant'] = {'distance': d4, 'falsified': d4 < 0.03}

    # T5: Inverted
    print("\n[z1903] T5: Inverted Telemetry")
    inv_telem = 1.0 - real_telem.clamp(0, 1)
    d5 = signature_distance(real_sig, compute_signature(model, x_test, inv_telem, device))
    print(f"  Distance: {d5:.4f}")
    tests['T5_inverted'] = {'distance': d5, 'falsified': d5 < 0.05}

    # T6: Weight divergence test - unique to hypernetworks
    print("\n[z1903] T6: Weight Generation Divergence")
    model.eval()
    with torch.no_grad():
        # Get generated weights with real vs random telemetry
        hyper_block = model.hyper_blocks[0]
        q_real = hyper_block.attn.q_hyper.telem_proj(real_telem.unsqueeze(0))
        q_rand = hyper_block.attn.q_hyper.telem_proj(torch.rand(1, 20, device=device))

        weight_divergence = (q_real - q_rand).abs().mean().item()
        print(f"  Q-projection divergence: {weight_divergence:.4f}")

    tests['T6_weight_divergence'] = {
        'divergence': weight_divergence,
        'falsified': weight_divergence < 0.01,  # Should be substantial
    }

    results['falsification_tests'] = tests

    num_falsified = sum(1 for t in tests.values() if t['falsified'])
    results['num_falsified'] = num_falsified
    results['num_total'] = len(tests)
    results['status'] = 'FALSIFIED' if num_falsified > 0 else 'SURVIVED ALL TESTS'

    print(f"\n{'='*60}")
    print(f"[z1903] RESULTS")
    print(f"{'='*60}")
    for name, t in tests.items():
        status = "FALSIFIED" if t['falsified'] else "SURVIVED"
        print(f"  {status} {name}")

    print(f"\n[z1903] Tests survived: {len(tests) - num_falsified}/{len(tests)}")
    print(f"[z1903] Status: {results['status']}")

    telemetry.stop()

    # Save
    results_path = Path(__file__).parent.parent / "results" / "z1903_hypernetwork_embodiment.json"
    with open(results_path, 'w') as f:
        json.dump(results, f, indent=2, default=str)
    print(f"\n[z1903] Results saved to {results_path}")

    return results


if __name__ == "__main__":
    run_experiment()
